// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package MeetingRoomNotificationService;

public interface DeviceSupplyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meetingroomnotification.DeviceSupplyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 paper = 2;</code>
   */
  int getPaper();

  /**
   * <code>int32 cartridge = 3;</code>
   */
  int getCartridge();
}
