// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package MeetingRoomNotificationService;

public interface DeviceSupplyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meetingroomnotification.DeviceSupplyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
