// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package MeetingRoomNotificationService;

public final class MeetingRoomNotificationServiceImpl {
  private MeetingRoomNotificationServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meetingroomnotification_DeviceSupplyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meetingroomnotification_DeviceSupplyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meetingroomnotification_DeviceSupplyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meetingroomnotification_DeviceSupplyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\022\027meetingroomnotificatio" +
      "n\"E\n\023DeviceSupplyRequest\022\014\n\004name\030\001 \001(\t\022\r" +
      "\n\005paper\030\002 \001(\005\022\021\n\tcartridge\030\003 \001(\005\"8\n\024Devi" +
      "ceSupplyResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007mes" +
      "sage\030\002 \001(\t2\217\001\n\036MeetingRoomNotificationSe" +
      "rvice\022m\n\014deviceSupply\022,.meetingroomnotif" +
      "ication.DeviceSupplyRequest\032-.meetingroo" +
      "mnotification.DeviceSupplyResponse\"\000BF\n\036" +
      "MeetingRoomNotificationServiceB\"MeetingR" +
      "oomNotificationServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_meetingroomnotification_DeviceSupplyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_meetingroomnotification_DeviceSupplyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meetingroomnotification_DeviceSupplyRequest_descriptor,
        new java.lang.String[] { "Name", "Paper", "Cartridge", });
    internal_static_meetingroomnotification_DeviceSupplyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_meetingroomnotification_DeviceSupplyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meetingroomnotification_DeviceSupplyResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
