// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package MeetingRoomAvailabilityService;

public interface BookingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meetingroomavailability.BookingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string date = 2;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 2;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string start_time = 3;</code>
   */
  java.lang.String getStartTime();
  /**
   * <code>string start_time = 3;</code>
   */
  com.google.protobuf.ByteString
      getStartTimeBytes();

  /**
   * <code>int32 duration = 4;</code>
   */
  int getDuration();
}
