// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package MeetingRoomAvailabilityService;

public interface BookingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meetingroomavailability.BookingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_booked = 1;</code>
   */
  boolean getIsBooked();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string res_num = 3;</code>
   */
  java.lang.String getResNum();
  /**
   * <code>string res_num = 3;</code>
   */
  com.google.protobuf.ByteString
      getResNumBytes();
}
