// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package MeetingRoomAvailabilityService;

public interface MeetingRoomOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meetingroomavailability.MeetingRoom)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 capacity = 3;</code>
   */
  int getCapacity();

  /**
   * <code>string equipment = 4;</code>
   */
  java.lang.String getEquipment();
  /**
   * <code>string equipment = 4;</code>
   */
  com.google.protobuf.ByteString
      getEquipmentBytes();

  /**
   * <code>bool available = 5;</code>
   */
  boolean getAvailable();
}
