// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package MeetingRoomAvailabilityService;

public final class MeetingRoomAvailabilityServiceImpl {
  private MeetingRoomAvailabilityServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meetingroomavailability_MeetingRoom_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meetingroomavailability_MeetingRoom_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meetingroomavailability_BookingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meetingroomavailability_BookingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meetingroomavailability_BookingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meetingroomavailability_BookingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\027meetingroomavailabilit" +
      "y\"_\n\013MeetingRoom\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001" +
      "(\t\022\020\n\010capacity\030\003 \001(\005\022\021\n\tequipment\030\004 \001(\t\022" +
      "\021\n\tavailable\030\005 \001(\010\"P\n\016BookingRequest\022\n\n\002" +
      "id\030\001 \001(\t\022\014\n\004date\030\002 \001(\t\022\022\n\nstart_time\030\003 \001" +
      "(\t\022\020\n\010duration\030\004 \001(\005\"F\n\017BookingResponse\022" +
      "\021\n\tis_booked\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\022\017\n\007r" +
      "es_num\030\003 \001(\t2\210\001\n\036MeetingRoomAvailability" +
      "Service\022f\n\017BookMeetingRoom\022\'.meetingroom" +
      "availability.BookingRequest\032(.meetingroo" +
      "mavailability.BookingResponse\"\000BF\n\036Meeti" +
      "ngRoomAvailabilityServiceB\"MeetingRoomAv" +
      "ailabilityServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_meetingroomavailability_MeetingRoom_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_meetingroomavailability_MeetingRoom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meetingroomavailability_MeetingRoom_descriptor,
        new java.lang.String[] { "Id", "Name", "Capacity", "Equipment", "Available", });
    internal_static_meetingroomavailability_BookingRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_meetingroomavailability_BookingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meetingroomavailability_BookingRequest_descriptor,
        new java.lang.String[] { "Id", "Date", "StartTime", "Duration", });
    internal_static_meetingroomavailability_BookingResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_meetingroomavailability_BookingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meetingroomavailability_BookingResponse_descriptor,
        new java.lang.String[] { "IsBooked", "Message", "ResNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
