// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package MeetingRoomManagementService;

public interface AddMeetingRoomResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meetingroommanagement.AddMeetingRoomResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 3;</code>
   */
  java.util.List<MeetingRoomManagementService.UpdatedRoom> 
      getUpdatedRoomsList();
  /**
   * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 3;</code>
   */
  MeetingRoomManagementService.UpdatedRoom getUpdatedRooms(int index);
  /**
   * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 3;</code>
   */
  int getUpdatedRoomsCount();
  /**
   * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 3;</code>
   */
  java.util.List<? extends MeetingRoomManagementService.UpdatedRoomOrBuilder> 
      getUpdatedRoomsOrBuilderList();
  /**
   * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 3;</code>
   */
  MeetingRoomManagementService.UpdatedRoomOrBuilder getUpdatedRoomsOrBuilder(
      int index);
}
