// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package MeetingRoomManagementService;

public interface AddMeetingRoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meetingroommanagement.AddMeetingRoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 capacity = 3;</code>
   */
  int getCapacity();

  /**
   * <code>string equipment = 4;</code>
   */
  java.lang.String getEquipment();
  /**
   * <code>string equipment = 4;</code>
   */
  com.google.protobuf.ByteString
      getEquipmentBytes();
}
