// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package MeetingRoomManagementService;

public final class MeetingRoomManagementServiceImpl {
  private MeetingRoomManagementServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meetingroommanagement_UpdatedRoom_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meetingroommanagement_UpdatedRoom_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meetingroommanagement_AddMeetingRoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meetingroommanagement_AddMeetingRoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meetingroommanagement_AddMeetingRoomResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meetingroommanagement_AddMeetingRoomResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meetingroommanagement_UpdateMeetingRoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meetingroommanagement_UpdateMeetingRoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meetingroommanagement_UpdateMeetingRoomResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meetingroommanagement_UpdateMeetingRoomResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\022\025meetingroommanagement\"" +
      "_\n\013UpdatedRoom\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t" +
      "\022\020\n\010capacity\030\003 \001(\005\022\021\n\tequipment\030\004 \001(\t\022\021\n" +
      "\tavailable\030\005 \001(\010\"V\n\025AddMeetingRoomReques" +
      "t\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010capacity\030" +
      "\003 \001(\005\022\021\n\tequipment\030\004 \001(\t\"u\n\026AddMeetingRo" +
      "omResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002" +
      " \001(\t\0229\n\rupdated_rooms\030\003 \003(\0132\".meetingroo" +
      "mmanagement.UpdatedRoom\"Y\n\030UpdateMeeting" +
      "RoomRequest\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n" +
      "\010capacity\030\003 \001(\005\022\021\n\tequipment\030\004 \001(\t\"V\n\031Up" +
      "dateMeetingRoomResponse\0229\n\rupdated_rooms" +
      "\030\001 \003(\0132\".meetingroommanagement.UpdatedRo" +
      "om2\211\002\n\034MeetingRoomManagementService\022o\n\016A" +
      "ddMeetingRoom\022,.meetingroommanagement.Ad" +
      "dMeetingRoomRequest\032-.meetingroommanagem" +
      "ent.AddMeetingRoomResponse\"\000\022x\n\021UpdateMe" +
      "etingRoom\022/.meetingroommanagement.Update" +
      "MeetingRoomRequest\0320.meetingroommanageme" +
      "nt.UpdateMeetingRoomResponse\"\000BB\n\034Meetin" +
      "gRoomManagementServiceB MeetingRoomManag" +
      "ementServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_meetingroommanagement_UpdatedRoom_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_meetingroommanagement_UpdatedRoom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meetingroommanagement_UpdatedRoom_descriptor,
        new java.lang.String[] { "Id", "Name", "Capacity", "Equipment", "Available", });
    internal_static_meetingroommanagement_AddMeetingRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_meetingroommanagement_AddMeetingRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meetingroommanagement_AddMeetingRoomRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Capacity", "Equipment", });
    internal_static_meetingroommanagement_AddMeetingRoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_meetingroommanagement_AddMeetingRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meetingroommanagement_AddMeetingRoomResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "UpdatedRooms", });
    internal_static_meetingroommanagement_UpdateMeetingRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_meetingroommanagement_UpdateMeetingRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meetingroommanagement_UpdateMeetingRoomRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Capacity", "Equipment", });
    internal_static_meetingroommanagement_UpdateMeetingRoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_meetingroommanagement_UpdateMeetingRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meetingroommanagement_UpdateMeetingRoomResponse_descriptor,
        new java.lang.String[] { "UpdatedRooms", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
