// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package MeetingRoomManagementService;

/**
 * Protobuf type {@code meetingroommanagement.UpdateMeetingRoomResponse}
 */
public  final class UpdateMeetingRoomResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:meetingroommanagement.UpdateMeetingRoomResponse)
    UpdateMeetingRoomResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateMeetingRoomResponse.newBuilder() to construct.
  private UpdateMeetingRoomResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateMeetingRoomResponse() {
    updatedRooms_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateMeetingRoomResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              updatedRooms_ = new java.util.ArrayList<MeetingRoomManagementService.UpdatedRoom>();
              mutable_bitField0_ |= 0x00000001;
            }
            updatedRooms_.add(
                input.readMessage(MeetingRoomManagementService.UpdatedRoom.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        updatedRooms_ = java.util.Collections.unmodifiableList(updatedRooms_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MeetingRoomManagementService.MeetingRoomManagementServiceImpl.internal_static_meetingroommanagement_UpdateMeetingRoomResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MeetingRoomManagementService.MeetingRoomManagementServiceImpl.internal_static_meetingroommanagement_UpdateMeetingRoomResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MeetingRoomManagementService.UpdateMeetingRoomResponse.class, MeetingRoomManagementService.UpdateMeetingRoomResponse.Builder.class);
  }

  public static final int UPDATED_ROOMS_FIELD_NUMBER = 1;
  private java.util.List<MeetingRoomManagementService.UpdatedRoom> updatedRooms_;
  /**
   * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
   */
  public java.util.List<MeetingRoomManagementService.UpdatedRoom> getUpdatedRoomsList() {
    return updatedRooms_;
  }
  /**
   * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
   */
  public java.util.List<? extends MeetingRoomManagementService.UpdatedRoomOrBuilder> 
      getUpdatedRoomsOrBuilderList() {
    return updatedRooms_;
  }
  /**
   * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
   */
  public int getUpdatedRoomsCount() {
    return updatedRooms_.size();
  }
  /**
   * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
   */
  public MeetingRoomManagementService.UpdatedRoom getUpdatedRooms(int index) {
    return updatedRooms_.get(index);
  }
  /**
   * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
   */
  public MeetingRoomManagementService.UpdatedRoomOrBuilder getUpdatedRoomsOrBuilder(
      int index) {
    return updatedRooms_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < updatedRooms_.size(); i++) {
      output.writeMessage(1, updatedRooms_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < updatedRooms_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, updatedRooms_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MeetingRoomManagementService.UpdateMeetingRoomResponse)) {
      return super.equals(obj);
    }
    MeetingRoomManagementService.UpdateMeetingRoomResponse other = (MeetingRoomManagementService.UpdateMeetingRoomResponse) obj;

    boolean result = true;
    result = result && getUpdatedRoomsList()
        .equals(other.getUpdatedRoomsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUpdatedRoomsCount() > 0) {
      hash = (37 * hash) + UPDATED_ROOMS_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatedRoomsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MeetingRoomManagementService.UpdateMeetingRoomResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MeetingRoomManagementService.UpdateMeetingRoomResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MeetingRoomManagementService.UpdateMeetingRoomResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MeetingRoomManagementService.UpdateMeetingRoomResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MeetingRoomManagementService.UpdateMeetingRoomResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MeetingRoomManagementService.UpdateMeetingRoomResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MeetingRoomManagementService.UpdateMeetingRoomResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MeetingRoomManagementService.UpdateMeetingRoomResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MeetingRoomManagementService.UpdateMeetingRoomResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MeetingRoomManagementService.UpdateMeetingRoomResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MeetingRoomManagementService.UpdateMeetingRoomResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MeetingRoomManagementService.UpdateMeetingRoomResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MeetingRoomManagementService.UpdateMeetingRoomResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meetingroommanagement.UpdateMeetingRoomResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meetingroommanagement.UpdateMeetingRoomResponse)
      MeetingRoomManagementService.UpdateMeetingRoomResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MeetingRoomManagementService.MeetingRoomManagementServiceImpl.internal_static_meetingroommanagement_UpdateMeetingRoomResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MeetingRoomManagementService.MeetingRoomManagementServiceImpl.internal_static_meetingroommanagement_UpdateMeetingRoomResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MeetingRoomManagementService.UpdateMeetingRoomResponse.class, MeetingRoomManagementService.UpdateMeetingRoomResponse.Builder.class);
    }

    // Construct using MeetingRoomManagementService.UpdateMeetingRoomResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUpdatedRoomsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (updatedRoomsBuilder_ == null) {
        updatedRooms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        updatedRoomsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MeetingRoomManagementService.MeetingRoomManagementServiceImpl.internal_static_meetingroommanagement_UpdateMeetingRoomResponse_descriptor;
    }

    @java.lang.Override
    public MeetingRoomManagementService.UpdateMeetingRoomResponse getDefaultInstanceForType() {
      return MeetingRoomManagementService.UpdateMeetingRoomResponse.getDefaultInstance();
    }

    @java.lang.Override
    public MeetingRoomManagementService.UpdateMeetingRoomResponse build() {
      MeetingRoomManagementService.UpdateMeetingRoomResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public MeetingRoomManagementService.UpdateMeetingRoomResponse buildPartial() {
      MeetingRoomManagementService.UpdateMeetingRoomResponse result = new MeetingRoomManagementService.UpdateMeetingRoomResponse(this);
      int from_bitField0_ = bitField0_;
      if (updatedRoomsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          updatedRooms_ = java.util.Collections.unmodifiableList(updatedRooms_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.updatedRooms_ = updatedRooms_;
      } else {
        result.updatedRooms_ = updatedRoomsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MeetingRoomManagementService.UpdateMeetingRoomResponse) {
        return mergeFrom((MeetingRoomManagementService.UpdateMeetingRoomResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MeetingRoomManagementService.UpdateMeetingRoomResponse other) {
      if (other == MeetingRoomManagementService.UpdateMeetingRoomResponse.getDefaultInstance()) return this;
      if (updatedRoomsBuilder_ == null) {
        if (!other.updatedRooms_.isEmpty()) {
          if (updatedRooms_.isEmpty()) {
            updatedRooms_ = other.updatedRooms_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUpdatedRoomsIsMutable();
            updatedRooms_.addAll(other.updatedRooms_);
          }
          onChanged();
        }
      } else {
        if (!other.updatedRooms_.isEmpty()) {
          if (updatedRoomsBuilder_.isEmpty()) {
            updatedRoomsBuilder_.dispose();
            updatedRoomsBuilder_ = null;
            updatedRooms_ = other.updatedRooms_;
            bitField0_ = (bitField0_ & ~0x00000001);
            updatedRoomsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUpdatedRoomsFieldBuilder() : null;
          } else {
            updatedRoomsBuilder_.addAllMessages(other.updatedRooms_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MeetingRoomManagementService.UpdateMeetingRoomResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MeetingRoomManagementService.UpdateMeetingRoomResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<MeetingRoomManagementService.UpdatedRoom> updatedRooms_ =
      java.util.Collections.emptyList();
    private void ensureUpdatedRoomsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        updatedRooms_ = new java.util.ArrayList<MeetingRoomManagementService.UpdatedRoom>(updatedRooms_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        MeetingRoomManagementService.UpdatedRoom, MeetingRoomManagementService.UpdatedRoom.Builder, MeetingRoomManagementService.UpdatedRoomOrBuilder> updatedRoomsBuilder_;

    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public java.util.List<MeetingRoomManagementService.UpdatedRoom> getUpdatedRoomsList() {
      if (updatedRoomsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(updatedRooms_);
      } else {
        return updatedRoomsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public int getUpdatedRoomsCount() {
      if (updatedRoomsBuilder_ == null) {
        return updatedRooms_.size();
      } else {
        return updatedRoomsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public MeetingRoomManagementService.UpdatedRoom getUpdatedRooms(int index) {
      if (updatedRoomsBuilder_ == null) {
        return updatedRooms_.get(index);
      } else {
        return updatedRoomsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public Builder setUpdatedRooms(
        int index, MeetingRoomManagementService.UpdatedRoom value) {
      if (updatedRoomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdatedRoomsIsMutable();
        updatedRooms_.set(index, value);
        onChanged();
      } else {
        updatedRoomsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public Builder setUpdatedRooms(
        int index, MeetingRoomManagementService.UpdatedRoom.Builder builderForValue) {
      if (updatedRoomsBuilder_ == null) {
        ensureUpdatedRoomsIsMutable();
        updatedRooms_.set(index, builderForValue.build());
        onChanged();
      } else {
        updatedRoomsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public Builder addUpdatedRooms(MeetingRoomManagementService.UpdatedRoom value) {
      if (updatedRoomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdatedRoomsIsMutable();
        updatedRooms_.add(value);
        onChanged();
      } else {
        updatedRoomsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public Builder addUpdatedRooms(
        int index, MeetingRoomManagementService.UpdatedRoom value) {
      if (updatedRoomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdatedRoomsIsMutable();
        updatedRooms_.add(index, value);
        onChanged();
      } else {
        updatedRoomsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public Builder addUpdatedRooms(
        MeetingRoomManagementService.UpdatedRoom.Builder builderForValue) {
      if (updatedRoomsBuilder_ == null) {
        ensureUpdatedRoomsIsMutable();
        updatedRooms_.add(builderForValue.build());
        onChanged();
      } else {
        updatedRoomsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public Builder addUpdatedRooms(
        int index, MeetingRoomManagementService.UpdatedRoom.Builder builderForValue) {
      if (updatedRoomsBuilder_ == null) {
        ensureUpdatedRoomsIsMutable();
        updatedRooms_.add(index, builderForValue.build());
        onChanged();
      } else {
        updatedRoomsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public Builder addAllUpdatedRooms(
        java.lang.Iterable<? extends MeetingRoomManagementService.UpdatedRoom> values) {
      if (updatedRoomsBuilder_ == null) {
        ensureUpdatedRoomsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, updatedRooms_);
        onChanged();
      } else {
        updatedRoomsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public Builder clearUpdatedRooms() {
      if (updatedRoomsBuilder_ == null) {
        updatedRooms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        updatedRoomsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public Builder removeUpdatedRooms(int index) {
      if (updatedRoomsBuilder_ == null) {
        ensureUpdatedRoomsIsMutable();
        updatedRooms_.remove(index);
        onChanged();
      } else {
        updatedRoomsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public MeetingRoomManagementService.UpdatedRoom.Builder getUpdatedRoomsBuilder(
        int index) {
      return getUpdatedRoomsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public MeetingRoomManagementService.UpdatedRoomOrBuilder getUpdatedRoomsOrBuilder(
        int index) {
      if (updatedRoomsBuilder_ == null) {
        return updatedRooms_.get(index);  } else {
        return updatedRoomsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public java.util.List<? extends MeetingRoomManagementService.UpdatedRoomOrBuilder> 
         getUpdatedRoomsOrBuilderList() {
      if (updatedRoomsBuilder_ != null) {
        return updatedRoomsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(updatedRooms_);
      }
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public MeetingRoomManagementService.UpdatedRoom.Builder addUpdatedRoomsBuilder() {
      return getUpdatedRoomsFieldBuilder().addBuilder(
          MeetingRoomManagementService.UpdatedRoom.getDefaultInstance());
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public MeetingRoomManagementService.UpdatedRoom.Builder addUpdatedRoomsBuilder(
        int index) {
      return getUpdatedRoomsFieldBuilder().addBuilder(
          index, MeetingRoomManagementService.UpdatedRoom.getDefaultInstance());
    }
    /**
     * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
     */
    public java.util.List<MeetingRoomManagementService.UpdatedRoom.Builder> 
         getUpdatedRoomsBuilderList() {
      return getUpdatedRoomsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        MeetingRoomManagementService.UpdatedRoom, MeetingRoomManagementService.UpdatedRoom.Builder, MeetingRoomManagementService.UpdatedRoomOrBuilder> 
        getUpdatedRoomsFieldBuilder() {
      if (updatedRoomsBuilder_ == null) {
        updatedRoomsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            MeetingRoomManagementService.UpdatedRoom, MeetingRoomManagementService.UpdatedRoom.Builder, MeetingRoomManagementService.UpdatedRoomOrBuilder>(
                updatedRooms_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        updatedRooms_ = null;
      }
      return updatedRoomsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:meetingroommanagement.UpdateMeetingRoomResponse)
  }

  // @@protoc_insertion_point(class_scope:meetingroommanagement.UpdateMeetingRoomResponse)
  private static final MeetingRoomManagementService.UpdateMeetingRoomResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MeetingRoomManagementService.UpdateMeetingRoomResponse();
  }

  public static MeetingRoomManagementService.UpdateMeetingRoomResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateMeetingRoomResponse>
      PARSER = new com.google.protobuf.AbstractParser<UpdateMeetingRoomResponse>() {
    @java.lang.Override
    public UpdateMeetingRoomResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateMeetingRoomResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateMeetingRoomResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateMeetingRoomResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public MeetingRoomManagementService.UpdateMeetingRoomResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

