// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package MeetingRoomManagementService;

public interface UpdateMeetingRoomResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meetingroommanagement.UpdateMeetingRoomResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
   */
  java.util.List<MeetingRoomManagementService.UpdatedRoom> 
      getUpdatedRoomsList();
  /**
   * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
   */
  MeetingRoomManagementService.UpdatedRoom getUpdatedRooms(int index);
  /**
   * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
   */
  int getUpdatedRoomsCount();
  /**
   * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
   */
  java.util.List<? extends MeetingRoomManagementService.UpdatedRoomOrBuilder> 
      getUpdatedRoomsOrBuilderList();
  /**
   * <code>repeated .meetingroommanagement.UpdatedRoom updated_rooms = 1;</code>
   */
  MeetingRoomManagementService.UpdatedRoomOrBuilder getUpdatedRoomsOrBuilder(
      int index);
}
